apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: labconfmap
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  labconfmap;
          location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
      }
    }