apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-pv-claim
  namespace: labapache
  labels:
    app: apache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi